version: "3"
services:
  inferno:
    build:
      context: ./
    volumes:
      - ./data:/opt/inferno/data
    ports:
      - "4567:4567"
    depends_on:
      - validator_service
  cqf_ruler:
    image: tacoma/cqf-ruler-preloaded:0.5.0.no-vs
    ports:
      - "8080:8080"
  validator_service:
    image: infernocommunity/fhir-validator-service:latest
    # Update this path to match your directory structure
    volumes:
      - ./lib/deqm_test_kit/igs:/home/igs
