version: "3"
services:
  inferno:
    build:
      context: ./
    volumes:
      - ./data:/opt/inferno/data
    ports:
      - "4567:4567"
    depends_on:
      - validator_service
  cqf_ruler:
    image: tacoma/cqf-ruler-preloaded:0.6.0.no-vs
    ports:
      - "8080:8080"
  validator_service:
    image: infernocommunity/fhir-validator-service:latest
    # Update this path to match your directory structure
    volumes:
      - ./lib/deqm_test_kit/igs:/home/igs
  fhir_validator_app:
    image: infernocommunity/fhir-validator-app
    depends_on:
      - validator_service
    environment:
      EXTERNAL_VALIDATOR_URL: http://localhost/validatorapi
      VALIDATOR_BASE_PATH: /validator
  nginx:
    image: nginx
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    command: [nginx, "-g", "daemon off;"]
    depends_on:
      - fhir_validator_app
  redis:
    image: redis
    volumes:
      - ./data/redis:/data
    command: redis-server --appendonly yes
  worker:
    build:
      context: ./
    volumes:
      - ./data:/opt/inferno/data
    command: bundle exec sidekiq -r ./worker.rb
    depends_on:
      - redis
  deqm_test_server:
    depends_on:
      - mongo
      - redis
    image: tacoma/deqm-test-server:latest
    environment:
      HOST: deqm_test_server
      PORT: 3000
      DB_HOST: mongo
      DB_PORT: 27017
      DB_NAME: deqm-test-server-dev
      REDIS_HOST: redis
      REDIS_PORT: 6379
      NODE_TLS_REJECT_UNAUTHORIZED: 0
      IMPORT_WORKERS: 2
      NDJSON_WORKERS: 2
    ports:
      - "3000:3000"
    command: npm start
  mongo:
    image: mongo:4.4.4
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
