version: "3"
services:
  inferno:
    build:
      context: ./
    volumes:
      - ./data:/opt/inferno/data
    ports:
      - "4567:4567"
    depends_on:
      - validator_service
  worker:
    build:
      context: ./
    volumes:
      - ./data:/opt/inferno/data
    command: bundle exec sidekiq -r ./worker.rb
    depends_on:
      - redis
  validator_service:
    extends:
      file: docker-compose.background.yml
      service: validator_service
  fhir_validator_app:
    extends:
      file: docker-compose.background.yml
      service: fhir_validator_app
  nginx:
    extends:
      file: docker-compose.background.yml
      service: nginx
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf
  redis:
    extends:
      file: docker-compose.background.yml
      service: redis
  deqm_test_server:
    depends_on:
      - mongo
      - redis
    image: mitrehealthdocker/deqm-test-server:latest
    environment:
      SERVER_HOST: deqm_test_server
      SERVER_PORT: 3000
      DB_HOST: mongo
      DB_PORT: 27017
      DB_NAME: deqm-test-server-dev
      REDIS_HOST: redis
      REDIS_PORT: 6379
      NODE_TLS_REJECT_UNAUTHORIZED: 0
      IMPORT_WORKERS: 1
      NDJSON_WORKERS: 1
      EXEC_WORKERS: 0
    ports:
      - "3000:3000"
    command: npm start
  mongo:
    image: mongo:4.4.4
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
