version: "3"
services:
  # validator_service:
  #   image: infernocommunity/fhir-validator-service
  #   volumes:
  #     - ./lib/deqm_test_kit/igs:/home/igs
  # fhir_validator_app:
  #   image: infernocommunity/fhir-validator-app
  #   depends_on:
  #     - validator_service
  #   environment:
  #     EXTERNAL_VALIDATOR_URL: http://localhost/validatorapi
  #     VALIDATOR_BASE_PATH: /validator
  hl7_validator_service:
    image: infernocommunity/inferno-resource-validator
    environment:
      # Defines how long validator sessions last if unused, in minutes:
      # Negative values mean sessions never expire, 0 means sessions immediately expire
      SESSION_CACHE_DURATION: -1
    volumes:
      - ./lib/davinci_dtr_test_kit/igs:/app/igs
      # To let the service share your local FHIR package cache,
      # uncomment the below line
      # - ~/.fhir:/home/ktor/.fhir
  nginx:
    image: nginx
    volumes:
      - ./config/nginx.background.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    command: [nginx, "-g", "daemon off;"]
    depends_on:
      - hl7_validator_service
      # - fhir_validator_app
  redis:
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - ./data/redis:/data
    command: redis-server --appendonly yes
  deqm_test_server:
    depends_on:
      - mongo
      - redis
    image: mitrehealthdocker/deqm-test-server:latest
    environment:
      SERVER_HOST: deqm_test_server
      SERVER_PORT: 3000
      DB_HOST: mongo
      DB_PORT: 27017
      DB_NAME: deqm-test-server-dev
      REDIS_HOST: redis
      REDIS_PORT: 6379
      NODE_TLS_REJECT_UNAUTHORIZED: 0
      IMPORT_WORKERS: 1
      NDJSON_WORKERS: 1
      EXEC_WORKERS: 0
    ports:
      - "3000:3000"
    command: npm start
  mongo:
    image: mongo:4.4.4
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
